format = """$username\
$os\
$directory\
$time\
$all"""

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[username]
style_user = "bold green"
show_always = true

[os]
disabled = false

[os.symbols]
# Arch = "ğŸ§ "
Arch = "ïŒƒ  "
# Windows = "î˜ª "

[package]
disabled = true

[erlang]
symbol = "â“” "

[nodejs]
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š "

[typst]
symbol = "t "

[time]
disabled = false
time_format = "%R"
style = "bold yellow"
# style = "bg:color_bg1"
# format = '[[âŒ›$time](fg:color_fg0 bg:color_bg1)]($style)'
format = '[[âŒ›$time ](fg:#808080 bg:none)]($style)'
# format = '[[ ïº $time ](fg:color_fg0 bg:color_bg1)]($style)'
